### ISSUE TITLE
 The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.

### ISSUE THREAD

**Issue by yuwencool** [wpydcr/LLM-Kit#27]
bitsandbytes: 0.41.0
cuda:11.8
python:3.9.18

**Comment by wpydcr** [comment]
Is it a linux environment?

**Comment by yuwencool** [comment]
Thank you for your reply, the issue has been resolved, but the framework does not seem to support Qwen1.5 at present, and the following error appears


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wpydcr/LLM-Kit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月17日(星期天) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wpydcr/LLM-Kit]  The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable. (Issue #27)





 
Is it a linux environment?

**Comment by wpydcr** [comment]
The current version only supports the model in the readme, and has not been updated to adapt it lately

**Comment by wpydcr** [comment]
The current version only supports the model in the readme, and has not been updated to adapt it lately
